import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Guards the branding a user or a third party actually sees, in BOTH shipped
 * bundles.
 *
 * This exists because an audit that looked clean was not. The packaged app was
 * checked for upstream branding by grepping `app.asar` — zero hits, declared
 * done. But the app ships two bundles: the Electron asar, built from `desktop/`,
 * and the ~77MB sidecar that `bun build --compile` produces from `src/`. Only
 * the asar was scanned. The sidecar held the default profile shown on first run
 * — `displayName: 'cc-haha'`, `subtitle: 'github.com/NanmiCoder/cc-haha'` — and
 * the desktop's own correct default is only a fallback for before the server
 * answers, so every fresh install showed the upstream's name and repository.
 *
 * Deliberately narrow. A blanket "no cc-haha anywhere" check flags twenty
 * legitimate things — the real `~/.claude/cc-haha` directory, internal symbols,
 * temp-file prefixes, wire headers — all of which NOTICE.md defers on purpose
 * because renaming them breaks installs or protocol contracts. A test that
 * cries wolf gets deleted, so this pins the signals that are unambiguous.
 */
const repoRoot = join(import.meta.dir, '..', '..')

/** The two trees the two shipped bundles are compiled from. */
const SHIPPED_TREES = ['src', 'desktop/src', 'desktop/electron', 'adapters']

function grep(pattern: string, tree: string): string[] {
  const result = Bun.spawnSync(
    ['grep', '-rn', '--include=*.ts', '--include=*.tsx', '--include=*.json', '-E', pattern, tree],
    { cwd: repoRoot },
  )
  return new TextDecoder()
    .decode(result.stdout)
    .split('\n')
    .filter(Boolean)
    // Tests may quote the old values as fixtures of a stored profile.
    .filter((line) => !/\.test\.tsx?:/.test(line))
}

describe('shipped bundles do not point at the upstream project', () => {
  // `cc-haha` is a live directory name and cannot be a signal. The upstream
  // *account* has no legitimate use in shipped code: every occurrence is either
  // a link home to the wrong repository or a default nobody rebranded.
  test.each(SHIPPED_TREES)('%s never names the upstream account', (tree) => {
    expect(grep('NanmiCoder', tree)).toEqual([])
  })

  test('the first-run profile names this product, on the server side', () => {
    // The specific regression. The server default wins over the desktop one, so
    // fixing only desktop/src still leaves a fresh install showing upstream.
    const source = readFileSync(
      join(repoRoot, 'src/server/services/desktopUiPreferencesService.ts'),
      'utf8',
    )
    expect(source).toContain("displayName: 'AI Agent SDX'")
    expect(source).toContain("const DEFAULT_PROFILE_SUBTITLE = 'github.com/berlee-max/SDX'")
  })

  test('the diagnostics bundle a user hands over names this product', () => {
    // Generated by the app and sent to whoever is helping; it led with the
    // previous product's name in both the README and the markdown report.
    const source = readFileSync(join(repoRoot, 'src/server/services/diagnosticsService.ts'), 'utf8')
    expect(source).toContain("'AI Agent SDX diagnostics bundle'")
    expect(source).toContain("'# AI Agent SDX recent diagnostics'")
    expect(source).not.toContain("'cc-haha diagnostics bundle'")
  })

  test('settings descriptions name this product', () => {
    // Schema `.describe()` text surfaces in the settings UI and in generated docs.
    const source = readFileSync(join(repoRoot, 'src/utils/settings/types.ts'), 'utf8')
    expect(source).not.toMatch(/describe\('[^']*cc-haha[^']*'\)/)
  })
})
