import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Guards the branding a user or a third party actually sees, in BOTH shipped
 * bundles.
 *
 * This exists because an audit that looked clean was not. The packaged app was
 * checked for upstream branding by grepping `app.asar` — zero hits, declared
 * done. But the app ships two bundles: the Electron asar, built from `desktop/`,
 * and the ~77MB sidecar that `bun build --compile` produces from `src/`. Only
 * the asar was scanned. The sidecar held the default profile shown on first run
 * — `displayName: 'cc-haha'`, `subtitle: 'github.com/NanmiCoder/cc-haha'` — and
 * the desktop's own correct default is only a fallback for before the server
 * answers, so every fresh install showed the upstream's name and repository.
 *
 * Deliberately narrow. A blanket "no cc-haha anywhere" check flags twenty
 * legitimate things — the real `~/.claude/cc-haha` directory, internal symbols,
 * temp-file prefixes, wire headers — all of which NOTICE.md defers on purpose
 * because renaming them breaks installs or protocol contracts. A test that
 * cries wolf gets deleted, so this pins the signals that are unambiguous.
 */
const repoRoot = join(import.meta.dir, '..', '..')

/** The two trees the two shipped bundles are compiled from. */
const SHIPPED_TREES = ['src', 'desktop/src', 'desktop/electron', 'adapters']

function grep(pattern: string, tree: string): string[] {
  const result = Bun.spawnSync(
    ['grep', '-rn', '--include=*.ts', '--include=*.tsx', '--include=*.json', '-E', pattern, tree],
    { cwd: repoRoot },
  )
  return new TextDecoder()
    .decode(result.stdout)
    .split('\n')
    .filter(Boolean)
    // Tests may quote the old values as fixtures of a stored profile.
    .filter((line) => !/\.test\.tsx?:/.test(line))
}

describe('shipped bundles do not point at the upstream project', () => {
  // `cc-haha` is a live directory name and cannot be a signal. The upstream
  // *account* has no legitimate use in shipped code: every occurrence is either
  // a link home to the wrong repository or a default nobody rebranded.
  test.each(SHIPPED_TREES)('%s never names the upstream account', (tree) => {
    expect(grep('NanmiCoder', tree)).toEqual([])
  })

  test('the first-run profile names this product, on the server side', () => {
    // The specific regression. The server default wins over the desktop one, so
    // fixing only desktop/src still leaves a fresh install showing upstream.
    const source = readFileSync(
      join(repoRoot, 'src/server/services/desktopUiPreferencesService.ts'),
      'utf8',
    )
    expect(source).toContain("displayName: 'AI Agent SDX'")
    expect(source).toContain("const DEFAULT_PROFILE_SUBTITLE = 'github.com/berlee-max/SDX'")
  })

  test('the diagnostics bundle a user hands over names this product', () => {
    // Generated by the app and sent to whoever is helping; it led with the
    // previous product's name in both the README and the markdown report.
    const source = readFileSync(join(repoRoot, 'src/server/services/diagnosticsService.ts'), 'utf8')
    expect(source).toContain("'AI Agent SDX diagnostics bundle'")
    expect(source).toContain("'# AI Agent SDX recent diagnostics'")
    expect(source).not.toContain("'cc-haha diagnostics bundle'")
  })

  test('outbound User-Agents do not claim to be the upstream project', () => {
    // These go to third parties on every request, so they are the one place the
    // old name is not just stale but a false claim about who is calling. Two
    // existed: `cc-haha/$VERSION` to opencode.ai and `cc-haha-grok-oauth/1.0`
    // to Grok's OAuth endpoint.
    //
    // Lowercase and space-free on purpose — RFC 7231 product tokens cannot
    // contain spaces, so "AI Agent SDX/1.0" would be a malformed header.
    const presets = readFileSync(join(repoRoot, 'src/server/config/providerPresets.json'), 'utf8')
    expect(presets).toContain('"User-Agent": "sdx/$VERSION"')
    expect(presets).not.toMatch(/"User-Agent":\s*"cc-haha/)

    const grok = readFileSync(join(repoRoot, 'src/services/grokAuth/client.ts'), 'utf8')
    expect(grok).toContain("'User-Agent': 'sdx-grok-oauth/1.0'")

    // The Claude Code user agents are a different thing and stay: they identify
    // the engine this wraps, and Anthropic's API keys behaviour off `claude-cli/`.
    expect(readFileSync(join(repoRoot, 'src/utils/http.ts'), 'utf8')).toContain('Claude-User')
  })

  test('the Windows default install directory is the short, space-free one', () => {
    // electron-builder derives it from productName, which would give
    // "...\\Programs\\AI Agent SDX". The override lives in customInit because
    // that is the only hook that runs AFTER initMultiUser has resolved $INSTDIR.
    const nsh = readFileSync(join(repoRoot, 'desktop/build/installer.nsh'), 'utf8')
    expect(nsh).toContain('!define /ifndef SDX_INSTALL_DIR_NAME "sdx-aiagent"')

    const customInit = nsh.slice(nsh.indexOf('!macro customInit'))
    expect(customInit).toContain('StrCpy $INSTDIR "$R2\\${SDX_INSTALL_DIR_NAME}"')

    // The two cases that must still win over the default. Losing the registry
    // check relocates an upgrade and orphans the old copy; losing the /D check
    // breaks silent installs and the Windows installer smoke test.
    expect(customInit).toMatch(/ReadRegStr \$R1 HKCU "\$\{INSTALL_REGISTRY_KEY\}" InstallLocation/)
    expect(customInit).toContain('!insertmacro GetDParameter $R0')

    // Exactly one definition — NSIS errors on a duplicate macro name, and this
    // file already had a customInit for the legacy-data recovery.
    expect(nsh.match(/^!macro customInit$/gm)).toHaveLength(1)
  })

  test('settings descriptions name this product', () => {
    // Schema `.describe()` text surfaces in the settings UI and in generated docs.
    const source = readFileSync(join(repoRoot, 'src/utils/settings/types.ts'), 'utf8')
    expect(source).not.toMatch(/describe\('[^']*cc-haha[^']*'\)/)
  })
})
